GET http://localhost:8001/train-member/hello
Accept: application/json

### 网关接口转发地址
GET http://localhost:8000/train-member/hello
Accept: application/json

### 测试MyBatis
GET http://localhost:8000/train-member/member/count
Accept: application/json

### 测试注册
POST http://localhost:8000/train-member/member/register
Content-Type: application/x-www-form-urlencoded

mobile=15565946702

### 测试验证码发送
POST http://localhost:8000/train-member/member/send-code
Content-Type: application/json

{
  "mobile": 15565946702
}


### 测试登录
POST http://localhost:8000/train-member/member/login
Content-Type: application/json

{
  "mobile": 15565946703,
  "code": 8888
}
> {%
    client.log(JSON.stringify(response.body));
    client.log(JSON.stringify(response.body.content.token));
    client.global.set("token", response.body.content.token);
%}

### 测试Token拦截
GET http://localhost:8000/train-member/hello
Accept: application/json
token: {{token}}