GET http://localhost:8001/train-member/hello
Accept: application/json

### 网关接口转发地址
GET http://localhost:8000/train-member/hello
Accept: application/json

### 测试MyBatis
GET http://localhost:8000/train-member/member/count
Accept: application/json

### 测试注册
POST http://localhost:8000/train-member/member/register
Content-Type: application/x-www-form-urlencoded

mobile=23131